---
version: '3.4'
services:
  kafka:
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_HOST_NAME: kafka
    build:
      context: .
      target: kafka
  connect:
    depends_on:
      - kafka
    hostname: connect
    container_name: connect
    build:
      context: .
      target: connect
    volumes:
      - ./output:/opt/output

